import type { StadiumEdge } from "./types";

export const STADIUM_EDGES: readonly StadiumEdge[] = [
  {
    id: "transport-north--gate-a",
    from: "transport-north",
    to: "gate-a",
    bidirectional: true,
    distanceMeters: 90,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 8,
    quietScore: 38,
    baselineCrowd: 0.55,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["transport-hub", "north-entry"],
  },
  {
    id: "gate-a--north",
    from: "gate-a",
    to: "concourse-north",
    bidirectional: true,
    distanceMeters: 72,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 9,
    quietScore: 43,
    baselineCrowd: 0.62,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["north-entry", "north-concourse"],
  },
  {
    id: "gate-b--east",
    from: "gate-b",
    to: "concourse-east",
    bidirectional: true,
    distanceMeters: 58,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 8,
    quietScore: 38,
    baselineCrowd: 0.64,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["east-concourse"],
  },
  {
    id: "gate-c--south",
    from: "gate-c",
    to: "concourse-south",
    bidirectional: true,
    distanceMeters: 60,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 8,
    quietScore: 42,
    baselineCrowd: 0.5,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["south-concourse"],
  },
  {
    id: "gate-d--west",
    from: "gate-d",
    to: "concourse-west",
    bidirectional: true,
    distanceMeters: 62,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 8,
    quietScore: 72,
    baselineCrowd: 0.28,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["west-concourse"],
  },
  {
    id: "north--east",
    from: "concourse-north",
    to: "concourse-east",
    bidirectional: true,
    distanceMeters: 118,
    kind: "walkway",
    stepFree: true,
    widthMeters: 7,
    quietScore: 34,
    baselineCrowd: 0.72,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["north-concourse", "east-concourse"],
  },
  {
    id: "east--south",
    from: "concourse-east",
    to: "concourse-south",
    bidirectional: true,
    distanceMeters: 116,
    kind: "walkway",
    stepFree: true,
    widthMeters: 7,
    quietScore: 45,
    baselineCrowd: 0.55,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["east-concourse", "south-concourse"],
  },
  {
    id: "south--west",
    from: "concourse-south",
    to: "concourse-west",
    bidirectional: true,
    distanceMeters: 112,
    kind: "walkway",
    stepFree: true,
    widthMeters: 7,
    quietScore: 68,
    baselineCrowd: 0.36,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["south-concourse", "west-concourse"],
  },
  {
    id: "west--north",
    from: "concourse-west",
    to: "concourse-north",
    bidirectional: true,
    distanceMeters: 120,
    kind: "walkway",
    stepFree: true,
    widthMeters: 8,
    quietScore: 86,
    baselineCrowd: 0.22,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["west-concourse", "north-concourse"],
  },
  {
    id: "north--stairs-north",
    from: "concourse-north",
    to: "stairs-north",
    bidirectional: true,
    distanceMeters: 14,
    kind: "walkway",
    stepFree: true,
    widthMeters: 4,
    quietScore: 38,
    baselineCrowd: 0.62,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["north-concourse"],
  },
  {
    id: "stairs-north--upper-north",
    from: "stairs-north",
    to: "upper-north-landing",
    bidirectional: true,
    distanceMeters: 18,
    kind: "stairs",
    stepFree: false,
    widthMeters: 4,
    quietScore: 34,
    baselineCrowd: 0.58,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["north-concourse", "upper-north"],
  },
  {
    id: "north--lift-north",
    from: "concourse-north",
    to: "lift-north",
    bidirectional: true,
    distanceMeters: 22,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 3,
    quietScore: 51,
    baselineCrowd: 0.68,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["north-concourse"],
  },
  {
    id: "lift-north--upper-north",
    from: "lift-north",
    to: "upper-north-landing",
    bidirectional: true,
    distanceMeters: 12,
    kind: "lift",
    stepFree: true,
    widthMeters: 2.2,
    quietScore: 50,
    baselineCrowd: 0.72,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["north-concourse", "upper-north"],
  },
  {
    id: "north--ramp-north",
    from: "concourse-north",
    to: "ramp-north",
    bidirectional: true,
    distanceMeters: 30,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 5,
    quietScore: 70,
    baselineCrowd: 0.34,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["north-concourse"],
  },
  {
    id: "ramp-north--upper-north",
    from: "ramp-north",
    to: "upper-north-landing",
    bidirectional: true,
    distanceMeters: 78,
    kind: "ramp",
    stepFree: true,
    widthMeters: 5,
    quietScore: 72,
    baselineCrowd: 0.3,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["north-concourse", "upper-north"],
  },
  {
    id: "west--lift-west",
    from: "concourse-west",
    to: "lift-west",
    bidirectional: true,
    distanceMeters: 24,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 4,
    quietScore: 84,
    baselineCrowd: 0.18,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["west-concourse"],
  },
  {
    id: "lift-west--upper-west",
    from: "lift-west",
    to: "upper-west-landing",
    bidirectional: true,
    distanceMeters: 14,
    kind: "lift",
    stepFree: true,
    widthMeters: 2.2,
    quietScore: 82,
    baselineCrowd: 0.2,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["west-concourse", "upper-north"],
  },
  {
    id: "upper-west--upper-north",
    from: "upper-west-landing",
    to: "upper-north-landing",
    bidirectional: true,
    distanceMeters: 92,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 5,
    quietScore: 88,
    baselineCrowd: 0.18,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["upper-north"],
  },
  {
    id: "upper-north--upper-east",
    from: "upper-north-landing",
    to: "upper-east-landing",
    bidirectional: true,
    distanceMeters: 104,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 5,
    quietScore: 47,
    baselineCrowd: 0.5,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["upper-north", "upper-east"],
  },
  {
    id: "upper-north--section-214",
    from: "upper-north-landing",
    to: "section-214",
    bidirectional: true,
    distanceMeters: 44,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 4,
    quietScore: 54,
    baselineCrowd: 0.48,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["upper-north"],
  },
  {
    id: "upper-east--section-305",
    from: "upper-east-landing",
    to: "section-305",
    bidirectional: true,
    distanceMeters: 48,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 4,
    quietScore: 44,
    baselineCrowd: 0.52,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["upper-east"],
  },
  {
    id: "east--section-110",
    from: "concourse-east",
    to: "section-110",
    bidirectional: true,
    distanceMeters: 50,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 4,
    quietScore: 36,
    baselineCrowd: 0.58,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["east-concourse"],
  },
  {
    id: "south--section-118",
    from: "concourse-south",
    to: "section-118",
    bidirectional: true,
    distanceMeters: 46,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 4,
    quietScore: 50,
    baselineCrowd: 0.46,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["south-concourse"],
  },
  {
    id: "north--accessible-toilet",
    from: "concourse-north",
    to: "accessible-toilet-north",
    bidirectional: true,
    distanceMeters: 28,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 3,
    quietScore: 62,
    baselineCrowd: 0.3,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["north-concourse"],
  },
  {
    id: "east--toilet-east",
    from: "concourse-east",
    to: "toilet-east",
    bidirectional: true,
    distanceMeters: 25,
    kind: "walkway",
    stepFree: true,
    widthMeters: 3,
    quietScore: 30,
    baselineCrowd: 0.6,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["east-concourse"],
  },
  {
    id: "east--medical-east",
    from: "concourse-east",
    to: "medical-east",
    bidirectional: true,
    distanceMeters: 22,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 3,
    quietScore: 67,
    baselineCrowd: 0.24,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["east-concourse"],
  },
  {
    id: "north--medical-north",
    from: "concourse-north",
    to: "medical-north",
    bidirectional: true,
    distanceMeters: 24,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 3,
    quietScore: 66,
    baselineCrowd: 0.3,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["north-concourse"],
  },
  {
    id: "west--water-west",
    from: "concourse-west",
    to: "water-west",
    bidirectional: true,
    distanceMeters: 23,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 3,
    quietScore: 75,
    baselineCrowd: 0.22,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["west-concourse"],
  },
  {
    id: "south--water-south",
    from: "concourse-south",
    to: "water-south",
    bidirectional: true,
    distanceMeters: 24,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 3,
    quietScore: 57,
    baselineCrowd: 0.36,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["south-concourse"],
  },
  {
    id: "gate-a--assistance",
    from: "gate-a",
    to: "assistance-gate-a",
    bidirectional: true,
    distanceMeters: 20,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 3,
    quietScore: 62,
    baselineCrowd: 0.28,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["north-entry"],
  },
  {
    id: "west--assistance-west",
    from: "concourse-west",
    to: "assistance-west",
    bidirectional: true,
    distanceMeters: 26,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 3,
    quietScore: 84,
    baselineCrowd: 0.2,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["west-concourse"],
  },
  {
    id: "south--food-south",
    from: "concourse-south",
    to: "food-south",
    bidirectional: true,
    distanceMeters: 30,
    kind: "walkway",
    stepFree: true,
    widthMeters: 5,
    quietScore: 24,
    baselineCrowd: 0.64,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["south-concourse"],
  },
  {
    id: "south--transport-south",
    from: "concourse-south",
    to: "transport-south",
    bidirectional: true,
    distanceMeters: 105,
    kind: "accessible-path",
    stepFree: true,
    widthMeters: 8,
    quietScore: 44,
    baselineCrowd: 0.44,
    status: "open",
    accessibilityObstructed: false,
    zoneIds: ["south-concourse", "transport-hub"],
  },
] as const;
