import type { StadiumNode } from "./types";

export const STADIUM_NODE_IDS = {
  gateA: "gate-a",
  gateB: "gate-b",
  gateC: "gate-c",
  gateD: "gate-d",
  section110: "section-110",
  section118: "section-118",
  section214: "section-214",
  section305: "section-305",
  northConcourse: "concourse-north",
  eastConcourse: "concourse-east",
  southConcourse: "concourse-south",
  westConcourse: "concourse-west",
  accessibleToiletNorth: "accessible-toilet-north",
  medicalEast: "medical-east",
  assistanceGateA: "assistance-gate-a",
  transportNorth: "transport-north",
} as const;

export const STADIUM_NODES: readonly StadiumNode[] = [
  {
    id: "gate-a",
    name: "Gate A",
    kind: "gate",
    zoneId: "north-entry",
    level: 0,
    position: { x: 50, y: 4 },
    accessible: true,
    quietScore: 44,
    description: "Primary north entrance with accessible screening lanes.",
  },
  {
    id: "gate-b",
    name: "Gate B",
    kind: "gate",
    zoneId: "east-concourse",
    level: 0,
    position: { x: 94, y: 48 },
    accessible: true,
    quietScore: 40,
    description: "East entrance serving lower-bowl sections.",
  },
  {
    id: "gate-c",
    name: "Gate C",
    kind: "gate",
    zoneId: "south-concourse",
    level: 0,
    position: { x: 50, y: 96 },
    accessible: true,
    quietScore: 38,
    description: "South entrance adjacent to shuttle drop-off.",
  },
  {
    id: "gate-d",
    name: "Gate D",
    kind: "gate",
    zoneId: "west-concourse",
    level: 0,
    position: { x: 6, y: 48 },
    accessible: true,
    quietScore: 60,
    description: "Lower-volume west entrance with step-free access.",
  },
  {
    id: "concourse-north",
    name: "North Concourse",
    kind: "concourse",
    zoneId: "north-concourse",
    level: 0,
    position: { x: 50, y: 22 },
    accessible: true,
    quietScore: 46,
    description: "Main circulation space for the north stand.",
  },
  {
    id: "concourse-east",
    name: "East Concourse",
    kind: "concourse",
    zoneId: "east-concourse",
    level: 0,
    position: { x: 78, y: 50 },
    accessible: true,
    quietScore: 39,
    description: "Main circulation space for the east stand.",
  },
  {
    id: "concourse-south",
    name: "South Concourse",
    kind: "concourse",
    zoneId: "south-concourse",
    level: 0,
    position: { x: 50, y: 78 },
    accessible: true,
    quietScore: 58,
    description: "Main circulation space for the south stand.",
  },
  {
    id: "concourse-west",
    name: "West Concourse",
    kind: "concourse",
    zoneId: "west-concourse",
    level: 0,
    position: { x: 22, y: 50 },
    accessible: true,
    quietScore: 82,
    description: "Quieter circulation space for the west stand.",
  },
  {
    id: "lift-north",
    name: "North Accessible Lift",
    kind: "lift",
    zoneId: "north-concourse",
    level: 0,
    position: { x: 56, y: 27 },
    accessible: true,
    quietScore: 52,
    description: "Staff-monitored lift connecting the concourse to level two.",
  },
  {
    id: "stairs-north",
    name: "North Stairs",
    kind: "stairs",
    zoneId: "north-concourse",
    level: 0,
    position: { x: 47, y: 29 },
    accessible: false,
    quietScore: 37,
    description: "Direct stairway to the upper north tier.",
  },
  {
    id: "ramp-north",
    name: "North Ramp",
    kind: "ramp",
    zoneId: "north-concourse",
    level: 0,
    position: { x: 64, y: 28 },
    accessible: true,
    quietScore: 70,
    description: "Wide step-free ramp to the upper north tier.",
  },
  {
    id: "upper-north-landing",
    name: "Upper North Landing",
    kind: "concourse",
    zoneId: "upper-north",
    level: 2,
    position: { x: 50, y: 36 },
    accessible: true,
    quietScore: 55,
    description: "Level-two landing serving sections 210 to 218.",
  },
  {
    id: "lift-west",
    name: "West Accessible Lift",
    kind: "lift",
    zoneId: "west-concourse",
    level: 0,
    position: { x: 30, y: 43 },
    accessible: true,
    quietScore: 84,
    description: "Low-traffic lift connecting west concourse to level two.",
  },
  {
    id: "upper-west-landing",
    name: "Upper West Landing",
    kind: "concourse",
    zoneId: "upper-north",
    level: 2,
    position: { x: 34, y: 38 },
    accessible: true,
    quietScore: 86,
    description: "Quiet level-two landing beside the sensory room.",
  },
  {
    id: "upper-east-landing",
    name: "Upper East Landing",
    kind: "concourse",
    zoneId: "upper-east",
    level: 3,
    position: { x: 67, y: 39 },
    accessible: true,
    quietScore: 48,
    description: "Level-three landing serving the east upper tier.",
  },
  {
    id: "section-110",
    name: "Section 110",
    kind: "section",
    zoneId: "east-concourse",
    level: 1,
    position: { x: 68, y: 53 },
    accessible: true,
    quietScore: 36,
    description: "Lower east seating section with wheelchair positions.",
  },
  {
    id: "section-118",
    name: "Section 118",
    kind: "section",
    zoneId: "south-concourse",
    level: 1,
    position: { x: 50, y: 68 },
    accessible: true,
    quietScore: 49,
    description: "Lower south seating section.",
  },
  {
    id: "section-214",
    name: "Section 214",
    kind: "section",
    zoneId: "upper-north",
    level: 2,
    position: { x: 50, y: 43 },
    accessible: true,
    quietScore: 52,
    description: "Upper north seating with accessible viewing platform.",
  },
  {
    id: "section-305",
    name: "Section 305",
    kind: "section",
    zoneId: "upper-east",
    level: 3,
    position: { x: 62, y: 46 },
    accessible: true,
    quietScore: 43,
    description: "Upper east seating section.",
  },
  {
    id: "accessible-toilet-north",
    name: "North Accessible Toilet",
    kind: "accessible-toilet",
    zoneId: "north-concourse",
    level: 0,
    position: { x: 43, y: 23 },
    accessible: true,
    quietScore: 64,
    description: "Radar-key accessible toilet with adult changing space.",
  },
  {
    id: "toilet-east",
    name: "East Toilets",
    kind: "toilet",
    zoneId: "east-concourse",
    level: 0,
    position: { x: 80, y: 43 },
    accessible: false,
    quietScore: 30,
    description: "General toilet facilities on the east concourse.",
  },
  {
    id: "medical-east",
    name: "East Medical Point",
    kind: "medical",
    zoneId: "east-concourse",
    level: 0,
    position: { x: 75, y: 43 },
    accessible: true,
    quietScore: 72,
    description: "Clinician-staffed first-aid and medical assessment point.",
  },
  {
    id: "medical-north",
    name: "North Medical Point",
    kind: "medical",
    zoneId: "north-concourse",
    level: 0,
    position: { x: 59, y: 21 },
    accessible: true,
    quietScore: 70,
    description: "First-aid point near the north entrance.",
  },
  {
    id: "water-west",
    name: "West Water Refill",
    kind: "water-refill",
    zoneId: "west-concourse",
    level: 0,
    position: { x: 22, y: 43 },
    accessible: true,
    quietScore: 78,
    description: "Two height-adjusted bottle refill taps.",
  },
  {
    id: "water-south",
    name: "South Water Refill",
    kind: "water-refill",
    zoneId: "south-concourse",
    level: 0,
    position: { x: 57, y: 77 },
    accessible: true,
    quietScore: 61,
    description: "Four bottle refill taps near the south food court.",
  },
  {
    id: "assistance-gate-a",
    name: "Gate A Assistance Desk",
    kind: "assistance-desk",
    zoneId: "north-entry",
    level: 0,
    position: { x: 57, y: 10 },
    accessible: true,
    quietScore: 65,
    description: "Multilingual guest and accessibility assistance desk.",
  },
  {
    id: "assistance-west",
    name: "West Assistance Desk",
    kind: "assistance-desk",
    zoneId: "west-concourse",
    level: 0,
    position: { x: 18, y: 56 },
    accessible: true,
    quietScore: 86,
    description: "Quiet guest-services and sensory-support desk.",
  },
  {
    id: "food-south",
    name: "South Food Court",
    kind: "food",
    zoneId: "south-concourse",
    level: 0,
    position: { x: 42, y: 77 },
    accessible: true,
    quietScore: 25,
    description: "Main south food and beverage area.",
  },
  {
    id: "transport-north",
    name: "North Station Pickup",
    kind: "transport-pickup",
    zoneId: "transport-hub",
    level: 0,
    position: { x: 50, y: 0 },
    accessible: true,
    quietScore: 35,
    description: "Accessible pedestrian link to North Stadium Station.",
  },
  {
    id: "transport-south",
    name: "South Shuttle Pickup",
    kind: "transport-pickup",
    zoneId: "transport-hub",
    level: 0,
    position: { x: 50, y: 100 },
    accessible: true,
    quietScore: 42,
    description: "Low-floor shuttle and accessible taxi pickup area.",
  },
] as const;
